#!/system/bin/sh

# disable google checkin services
if [ -e /data/data/com.google.android.gsf/databases/gservices.db ]; then
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 'false' where name = 'perform_market_checkin' and value = 'true'"
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 'false' where name = 'checkin_dropbox_upload:system_update' and value = 'true'"
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 0 where name = 'market_force_checkin' and value = -1"
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 0 where name = 'checkin_interval'"
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 0 where name = 'secure:bandwidth_checkin_stat_interval'"
fi

if [ -e /data/data/com.android.providers.settings/databases/settings.db ]; then
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update secure set value = 1 where name='adb_enabled'"
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update secure set value = 1 where name='development_settings_enabled'"
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update system set value = 0.5 where name='transition_animation_scale'"
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update system set value = 0.5 where name='animator_duration_scale'"
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update system set value = 1 where name='window_animation_scale'"
# allow deep sleep while charging
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update system set value = 0 where name = 'stay_on_while_plugged_in'"
# fix for location services (required for google now)
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update secure set value = 'network,gps' where name = 'location_providers_allowed'"
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update secure set value = 0 where name='mock_location'"
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update secure set value = 1 where name='assisted_gps_enabled'"
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update secure set value = 1 where name='use_location'"
fi

# clean out old wifi settings (they can cause issues)
busybox rm /data/misc/wifi/*

# defrag database files
for i in \
`busybox find /data -iname "*.db"`; 
do \
	/system/xbin/sqlite3 $i 'VACUUM;'; 
	/system/xbin/sqlite3 $i 'REINDEX;'; 
done;

if [ -d "/dbdata" ]; then
	for i in \
	`busybox find /dbdata -iname "*.db"`; 
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
	done;
fi;

if [ -d "/datadata" ]; then
	for i in \
	`busybox find /datadata -iname "*.db"`; 
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
	done;
fi;

for i in \
`busybox find /sdcard -iname "*.db"`; 
do \
	/system/xbin/sqlite3 $i 'VACUUM;'; 
	/system/xbin/sqlite3 $i 'REINDEX;'; 
done;

# fix permissions (just to ensure all is well)
sh /system/bin/fix_permissions -l -r

# set the correct backup transport
bmgr transport com.google.android.backup/.BackupTransportService

# remove this script
busybox mount -o remount,rw -t auto /system
busybox rm /system/etc/init.d/01runonce
busybox mount -o remount,ro -t auto /system

